### ISSUE TITLE
Disappearing Armor 1.12.2

### ISSUE THREAD

**Issue by The-Artificer** [zlainsama/CosmeticArmorReworked#39] opened 2020-02-15 21:11 UTC
If a player is wearing armor in their armor slots, and then hides it, not only will it disappear visually initially, but eventually it will be irretrievably deleted. The regular armor slots don't seem to always drop properly on death, and they will often be deleted on relog to the server while hidden as well. The version used is [CosmeticArmorReworked-1.12.2-v4a.jar]. This occurs with any armor, including vanilla armors. It should additionally be noted that both Armourer's Workshop and Moreplayermodels are present in the modpack as well as CosmeticArmor. This issue has been encountered by multiple players with no identifiable common thread besides the mod and modpack itself.

**Comment by The-Artificer** [comment] 2020-02-15 21:17
I have realized that this issue could possibly simply be due to durability running out on the items without players knowing and the item breaking. I will test this theory with spawned unbreakable armor to see if the issue is still replicable.

**Comment by zlainsama** [comment] 2020-02-16 05:16
If you put armors in your regular armor slots, they are still being used normally even if you hide them.
The cosmetic slots added by my mod are separate from your regular armor slots, and the visual effect of having different armors(or hiding them) on your player using those slots is actually only taking place on the client side, other mods and the server itself shouldn't even notice anything unusual unless they are specifically looking for them through a special API provided by my mod.

**Comment by The-Artificer** [comment] 2020-02-16 19:13
I have conducted some further testing, and have encountered multiple strange issues with cosmetic armor's intended functionality. The specific modfile is "CosmeticArmorReworked-1.12.2-v4a.jar". The issues themselves appear to be as follows:

1. Regular armor slots while hidden not only do not display on the player(As should happen), but additionally disappear within the inventory as well. I understand this is a clientside visual display matter, but it is very confusing and misleading for users, and also means that people can't see the current durability on their armor.
2. Equipped hidden armor is always deleted from regular armor slots when switching between survival and creative modes. In fact, creative mode armor slots simply eat and won't store or save any armor placed into them whatsoever while hidden. These items cannot be retrieved.

To be clear, all issues mentioned here are purely in regards to vanilla armor slots, the only difference is them being hidden. None of these issues take place if the armor is not hidden, and cosmetic slots are unused.

**Comment by zlainsama** [comment] 2020-02-16 21:50
Does this happen in singleplayer or a server?
If this happens in singleplayer, can you find out what other mods are causing incompatibility? As it works fine on it's own.
If this happens only on a server, is the server a normal forge server? Or others like spongeforge? Does this happen on a normal forge server? If not, can you find out what plugins are causing incompatibility?

**Comment by The-Artificer** [comment] 2020-02-17 00:10
It happens on a normal forge server. A private one for my friends, using
this list of mods:
https://gist.githubusercontent.com/The-Artificer/efb774980ba6ff219eb15bcc802a83eb/raw/32581c38edbb6583e3cc98d6140d83f94ea139ac/modlist.txt

**Comment by zlainsama** [comment] 2020-02-17 07:58
I have found the cause, it happens because Armourer's Workshop is doing the same thing as my mod, I might be able to fix it by altering some event handlers order.

**Comment by zlainsama** [comment] 2020-02-17 08:33
Fixed in 1.12.2-v4b.

**Closed by zlainsama** 2020-02-17 08:33 UTC
