### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheMprs** [zlainsama/CosmeticArmorReworked#21] opened 2017-07-03 14:59 UTC
whenever you write /kill and have a piece of armor in the normal armor area it causes a time out and for the lowest piece of armor to dissapear

**Comment by zlainsama** [comment] 2017-07-08 03:18
which version does this happen?

**Comment by TheMprs** [comment] 2017-07-08 09:00
CosmeticArmorReworked-1.12-v1

**Comment by zlainsama** [comment] 2017-07-09 03:19
I cannot reproduce this on my side.
Could you describe it more detailed? was it singleplayer or multiplayer? did it has other mods installed? if its multiplayer, was the server a non-standard forge server?

**Comment by zlainsama** [comment] 2017-07-09 03:20
Also, try updating forge to latest version might help.

**Comment by TheMprs** [comment] 2017-07-09 10:03
we had it on a normal forge version, we have yet to update forge but will do soon
we had simple harvest. ftb utils and veinminer installed

**Comment by LemADEC** [comment] 2018-06-03 16:43
is that still reproduced?

**Comment by TheMprs** [comment] 2018-06-04 13:10
bro, it has been a year, i dont even remember writing this

**Comment by zlainsama** [comment] 2019-05-10 02:15
closing this as it's 2019 now...

**Closed by zlainsama** 2019-05-10 02:15 UTC
